#!/usr/bin/env bash
# ============================================================
#  Renders ./data/hermes/config.yaml + ./data/hermes/.env from ../.env
#  (port of the HF kit's cont-init/02-write-config.sh, adapted for a VM:
#   services are separate containers, so upstreams are compose service names
#   instead of 127.0.0.1, and the agent binds 0.0.0.0 so Caddy can reach it —
#   Caddy stays the only entry point exposed to the internet)
#  Run:  bash kit/render-config.sh     (bootstrap.sh calls this for you)
# ============================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
H="$HERE/data/hermes"
mkdir -p "$H"

MODEL_ID="${HERMES_MODEL:-}"
WEB_BACKEND="${HERMES_WEB_BACKEND:-tavily}"

# --- public base URL (used by the dashboard for cookies/redirects) ---
if [ -n "${PUBLIC_BASE_URL:-}" ]; then
    BASE="${PUBLIC_BASE_URL%/}"
else
    SA="${SITE_ADDRESS:-:80}"
    case "$SA" in
        :*) IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
            # hostname -I is not available everywhere (e.g. bare Oracle Linux)
            if [ -z "${IP:-}" ]; then
                IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || true)"
            fi
            PORT="${SA#:}"
            if [ "$PORT" = "80" ]; then BASE="http://${IP:-localhost}"
            else BASE="http://${IP:-localhost}:${PORT}"; fi ;;
        *)  BASE="https://${SA}" ;;
    esac
fi

cat > "$H/config.yaml" <<EOF
# ==== auto-generated by vps/kit/render-config.sh — edit .env, not this file ====
model:
  provider: ninerouter
  default: "${MODEL_ID}"

providers:
  # 9Router — free/paid models you connect in its dashboard
  ninerouter:
    api: http://router:20128/v1
    key_env: NINEROUTER_API_KEY
    transport: chat_completions
    discover_models: true

  # OmniRouter — keyless web models (Qwen / Gemini / OpenCode guest)
  omnirouter:
    api: http://omnirouter:8080/v1
    key_env: OMNI_ROUTER_KEY
    transport: chat_completions
    discover_models: true

web:
  backend: ${WEB_BACKEND}
  keyless_fallback: true
  keyless_rescue: true
EOF

# stable session secret for the dashboard (persists in the data dir)
if [ ! -f "$H/.dash_secret" ]; then
    LC_ALL=C tr -dc 'a-f0-9' </dev/urandom 2>/dev/null | head -c 64 > "$H/.dash_secret" || true
fi
DASH_SECRET="$(cat "$H/.dash_secret" 2>/dev/null || true)"
[ -z "$DASH_SECRET" ] && DASH_SECRET="$(LC_ALL=C tr -dc 'a-f0-9' </dev/urandom 2>/dev/null | head -c 64 || true)"

DASH=0
if [ -n "${DASHBOARD_USERNAME:-}" ] && [ -n "${DASHBOARD_PASSWORD:-}" ]; then DASH=1; fi

{
  echo "# ==== auto-generated by vps/kit/render-config.sh ===="
  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"; fi
  if [ -n "${TELEGRAM_ALLOWED_USERS:-}" ]; then echo "TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}"; fi
  echo "HERMES_TIMEZONE=${HERMES_TIMEZONE:-UTC}"

  # ---- web-to-api: OpenAI-compatible API server on 8642 ----
  if [ -n "${HERMES_API_KEY:-}" ]; then
    echo "API_SERVER_ENABLED=true"
    echo "API_SERVER_KEY=${HERMES_API_KEY}"
    echo "API_SERVER_HOST=0.0.0.0"
    echo "API_SERVER_PORT=8642"
  else
    echo "API_SERVER_ENABLED=false"
  fi

  # ---- web dashboard on 9119 (behind Caddy at /hermes/) ----
  if [ "$DASH" = "1" ]; then
    echo "HERMES_DASHBOARD=1"
    echo "HERMES_DASHBOARD_PORT=9119"
    echo "HERMES_DASHBOARD_HOST=0.0.0.0"
    echo "HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${DASHBOARD_USERNAME}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${DASHBOARD_PASSWORD}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_SECRET=${DASH_SECRET}"
    echo "HERMES_DASHBOARD_PUBLIC_URL=${BASE}/hermes/"
  else
    echo "HERMES_DASHBOARD=0"
  fi

  # ---- provider keys referenced by config.yaml ----
  if [ -n "${NINEROUTER_API_KEY:-}" ]; then echo "NINEROUTER_API_KEY=${NINEROUTER_API_KEY}"; fi
  if [ -n "${OMNI_ROUTER_KEY:-}" ]; then echo "OMNI_ROUTER_KEY=${OMNI_ROUTER_KEY}"; fi
} > "$H/.env"

chmod 600 "$H/.env" "$H/.dash_secret" 2>/dev/null || true
echo "[render-config] wrote config.yaml + .env into $H"
echo "[render-config] model='${MODEL_ID:-<unset>}' dashboard=${DASH} public_url=${BASE}/hermes/"
